# Generated by Django 5.1.6 on 2025-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_interests',
            field=models.TextField(blank=True, help_text="Additional subjects you're interested in"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_style_auditory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_style_kinesthetic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_style_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_style_visual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_study_time',
            field=models.CharField(choices=[('short', 'Short bursts (25-30 minutes)'), ('medium', 'Medium sessions (30-60 minutes)'), ('long', 'Long sessions (1-2 hours)')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiz_preference',
            field=models.IntegerField(choices=[(1, 'Very helpful'), (2, 'Somewhat helpful'), (3, 'Neutral'), (4, 'Not very helpful'), (5, 'Not at all helpful')], default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='study_habits',
            field=models.TextField(blank=True, help_text='Describe your study habits'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(related_name='interested_users', to='users.subject'),
        ),
    ]
