# Generated by Django 5.2 on 2025-06-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='quiz_preference',
            field=models.IntegerField(choices=[(1, 'Not at all helpful'), (2, 'Not very helpful'), (3, 'Neutral'), (4, 'Somewhat Helpful'), (5, 'Very helpful')], default=3),
        ),
    ]
