# Generated by Django 5.1.6 on 2025-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subject_customuser_custom_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_study_time',
            field=models.CharField(choices=[('short', 'Short bursts'), ('medium', 'Medium sessions '), ('long', 'Long sessions')], default='medium', max_length=10),
        ),
    ]
