# Generated by Django 5.1.6 on 2025-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interest_alter_customuser_preferred_study_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='users.interest'),
        ),
    ]
