# Generated by Django 5.2 on 2025-05-20 17:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='diagram_image_url',
        ),
        migrations.CreateModel(
            name='DiagramImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('filename', models.CharField(default='diagram.png', max_length=255)),
                ('content_type', models.CharField(default='image/png', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_images', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagram Image',
                'verbose_name_plural': 'Diagram Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='diagram_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.diagramimage'),
        ),
    ]
