# Generated by Django 5.2 on 2025-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_diagram_image_url_diagramimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='diagram_image',
        ),
        migrations.AddField(
            model_name='message',
            name='mindmap_json_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quiz', 'Quiz'), ('diagram', 'Diagram'), ('mindmap', 'Mindmap')], default='text', max_length=20),
        ),
        migrations.DeleteModel(
            name='DiagramImage',
        ),
    ]
