# Generated by Django 5.2 on 2025-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_mindmap_json_data_alter_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='structured_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quiz', 'Quiz'), ('diagram', 'Diagram'), ('youtube', 'YouTube')], default='text', max_length=20),
        ),
    ]
