# Generated by Django 5.2 on 2025-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_edited_at_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mindmap_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
    ]
