# Generated by Django 5.2 on 2025-06-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_structured_content_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quiz', 'Quiz'), ('diagram', 'Diagram'), ('youtube', 'YouTube'), ('flashcard_update', 'Flashcard Update'), ('background_process', 'Background Process')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_html', models.TextField()),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=10)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='chat.chat')),
            ],
            options={
                'verbose_name': 'Chat Question Bank',
                'verbose_name_plural': 'Chat Question Banks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('confidence_level', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='chat.chat')),
            ],
            options={
                'verbose_name': 'Chat Flashcard',
                'verbose_name_plural': 'Chat Flashcards',
                'ordering': ['-created_at'],
                'unique_together': {('chat', 'term')},
            },
        ),
    ]
