# Generated by Django 5.2 on 2025-06-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_type_chatquestionbank_chatflashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='has_diagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='has_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='has_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quiz', 'Quiz'), ('diagram', 'Diagram'), ('youtube', 'YouTube'), ('flashcard_update', 'Flashcard Update'), ('background_process', 'Background Process'), ('mixed', 'Mixed Content')], default='text', max_length=20),
        ),
    ]
