# Generated by Django 5.2 on 2025-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_mindmap_html_alter_message_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mindmap_html',
        ),
        migrations.AddField(
            model_name='message',
            name='diagram_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
