# Generated by Django 5.2 on 2025-06-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_has_code_message_has_diagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mixed_content_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
