# Generated by Django 5.2 on 2025-06-22 16:45

import uuid

import django.db.models.deletion
from django.db import migrations, models

import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_mixed_content_data'),
    ]

    operations = [
        # Create the vector extension first
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),
        migrations.CreateModel(
            name='ChatVectorIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chunks', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('embedding_model', models.CharField(
                    default='all-MiniLM-L6-v2', max_length=100)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='vector_index', to='chat.chat')),
            ],
            options={
                'db_table': 'chat_vector_index',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='document_chunks', to='chat.chat')),
                ('rag_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='chunks', to='chat.chatragfile')),
            ],
            options={
                'db_table': 'chat_document_chunks',
                'indexes': [models.Index(fields=['chat', 'chunk_index'], name='chat_docume_chat_id_7655a4_idx'), models.Index(fields=['rag_file'], name='chat_docume_rag_fil_46f24c_idx')],
            },
        ),
    ]
